spring:
  main:
    web-application-type: servlet # or reactive, depending on your stack
#    shell:
#      interactive:
#        enabled: false

embabel:
  models:
    # Sets the primary model your agent uses to speak to users
    defaultLlm: "ministral-8b-2512"
  agent:


    platform:
      models:
        mistralai:
          api-key: 00LleM6p8YWPK1GMSDpWFLrNQKT5y4Ki
#            # If your version of Spring AI usesAdvisor / Options defaults, try enforcing native formatting:
#          options:
#            enable-native-structured-output: true

logging:
  level:
    root: INFO
#    com.embabel: DEBUG
#    org.springframework.ai: DEBUG